### ISSUE TITLE
Gatsby: Unhandled Rejection (TypeError): Cannot call a class as a function

### ISSUE THREAD

**Issue by gio00** [Spyna/react-store#15]
# Description

I am working with Gatsby and found this library as simpler alternative to redux. I have not found any example though so I was just trying to do the same thing as redux does with Gatsby (here an example: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux).

```
// gatsby-browser.js

import React from 'react';
import { createStore } from '@spyna/react-store';

export const wrapRootElement = createStore(({ element }) => element, { test: 1 });
``` 

# Result 
Getting this error
```
Unhandled Rejection (TypeError): Cannot call a class as a function
```

I do not know if the problem is with the library or from limitation of Gastby.

# Enviroment
```
  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16 
    react: ^16.8.6 => 16.8.6
    @spyna/react-store: ^1.2.0 => 1.2.0
```

**Comment by Spyna** [comment]
I'm not a master about Gatsby, however, as they say in the documentation https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement the `element` parameter is a ReactNode. (That is a "building block of React virtual DOM", even if it's not really accurate, imagine it as a *JSX* `<div>` or `<Root>` in the case of Gatsby). 

The function `createStore` is a High Order Component that accepts as input a React **Component**. 

So the problem is that you're passing the React Node `element`, but `createStore` expects a React Component. And that's where the error comes from. 

To make it work you can do the following in the file `wrap-with-provider.js` from the Gatsby sample:

```JavaScript
import React from "react"
import { createStore } from "@spyna/react-store"

//Create a React Component and pass it to createStore
class WrapperComponent extends React.Component {
  render() {
    return this.props.element
  }
}
//or shorter but less clear: const WrapperComponent = ({element}) => element

//create the store
const Wrapper = createStore(WrapperComponent, { count: 0 })

// eslint-disable-next-line react/display-name,react/prop-types
export default ({ element }) => {
//return the store
  return <Wrapper element={element} />
}

```

To consume the store you can edit the `layout.js` from the Gatsby example as following: 

```JavaScript
import { withStore } from "@spyna/react-store"

const Counter = function({ count, store }) {
  const increment = () => store.set("count", count + 1)
  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={increment}>Increment</button>
    </div>
  )
}

Counter.propTypes = {
  count: PropTypes.number.isRequired,
}

const ConnectedCounter = withStore(Counter, ["count"])
```

Et voilà, everything should work, please let me know if this works for you or you need more help.

**Comment by gio00** [comment]
Worked perfectly! Thank you! 

Now I have to save data to sessionStorage/localStorage to persist the data between refreshes and it should be good.
