### ISSUE TITLE
store values disappear on reload of page.

### ISSUE THREAD

**Issue by shameerahamed** [Spyna/react-store#18]
Store values are cleared on reloading of the page. Is this expected behaviour ?

**Comment by Spyna** [comment]
Yes, that's the expected behavior because the values of the store stay in memory. 
To make the store "survive" a page reload you have to save its state somewhere, for example the `localStorage` or `sessionStorage`. Next, when you initialize it using `createStore(Component)` you have to add the second parameter `initialState` reading it from where you saved. 

Example

```
//persist store
store
  .set('key', value)
  .then(() => {
     localStorage.setItem('stateOfMyApp', JSON.stringify(store.getState()));
   })
```
```
//initialize store
const initialState = JSON.read(localStorage.getItem('stateOfMyApp'))
createStore(App, initialState)

```

**Comment by shameerahamed** [comment]
👍 Thanks for your help, much appreciated.
